### ISSUE TITLE
Eager Beaver

### ISSUE THREAD

**Issue by InfraredRidingHood** [eflukx/OpalSCSI#1]
Hi, I think this is a really cool project and just want to say that If you need somebody to try out the hardware design I would be more than keen.  Can I ask if OpalScsi is going to be hardware only or do you plan on working on the BlueScsi firmware also?  

I think your board design ticks all the boxes especially being CC BY-SA 4.0 but the only thing I can suggest is giving it a termination on/off option.

Best wishes,

Stephen.

**Comment by eflukx** [comment]
Hi @InfraredRidingHood glad you like the project 👍🏻.

I have a classic Mac that I pulled from the attic and found it was not booting anymore... (external SCSI disk probably died, I don't really know). I looked for a "modern" replacement and found BlueSCSI, so wanted to try that. Only in my opinion the hardware is a bit clunky using a full BluePill on another board... As I had a strip GD32F103's lying around, I decided to design a new board, based on the BlueSCSI hardware (actually a blatant copy.. 😁). The intention is to use the BlueSCSI firmware directly, so this will be a HW-only project. I didn't come around to write up a proper `readme.md` to explain what this is about and just slapped the project files online.. ;)

I actually build two boards today:

![image](https://user-images.githubusercontent.com/996191/184981863-6a34d13a-7eb2-487d-adff-385055603987.png)

Will need to try them out with my Mac, keep you posted how that goes..
Btw I have more bare PCB's here, so if your interested will ship you one within Europe @shipping cost.

About the termination.. As there are 18 lines to be terminated i think 18 analog switches will be necessary to make the termination switchable. So that's quite a design change. Anyway this was intended to be plugged directly into the back of a computer so termination is desired in that case. Of course you can always build the design without the termination resistors and have a (fixed) non-terminated device.

**Comment by InfraredRidingHood** [comment]
Hi, many thanks for the reply and using the GD32F103 makes a lot of sense and makes the project even better!

Will you be using the https://github.com/androda/F4_BlueSCSI  firmware for this or the original BlueScsi firmware?

As soon as you have this working I will be delighted to make a fork of your HW and share some of my ideas. Thanks for offering me the PCB but since I’m not in Europe so I will just print some off with JLPCB.

Looking forward to your updates.

**Comment by 8waysanta** [comment]
Hi, have you had time to try OpalSCSI on your Macintosh yet?

**Comment by eflukx** [comment]
> Hi, have you had time to try OpalSCSI on your Macintosh yet?

As a matter of fact: 'No' ;)
I was able to flash the firmware onto the device, but as I've been in the middle of a move of our office, I've not been able to test it with the Mac... Expect to come back with results within a few days though.

**Comment by eflukx** [comment]
> Hi, have you had time to try OpalSCSI on your Macintosh yet?

Yes, today I finally had some time to try my build. I can confirm it worked like a charm first time! 😄 

Earlier I encountered some issues with flashing the firmware onto the device. I tried both JLink (cli) software and [probe-rs](https://probe.rs/), but somehow using these tools did not successfully/correctly flashed the bin file onto the STM32/GD32. So I first flashed the [generic USB bootloader](https://github.com/rogerclarkmelbourne/STM32duino-bootloader/tree/master/binaries) and thereafter I flashed the BlueSCSI firmware using the [BlueSCSI updater](https://github.com/erichelgeson/BlueSCSI-Updater)

Oh... what I noted when using this device, is that my Mac Plus doesn't power the device via SCSI termination power. I don't know if this is normal (and the Mac just does not provide termination power) or that maybe this is a setting (jumper) within the Mac of some kind. Anyway, with a USB supply connected things _just work_ ™️
